VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes

RGBLIGHT_ENABLE = yes

ENCODER_ENABLE = yes
VIAL_ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
QMK_SETTINGS = yes
